# Práctica 2
***
Rodriguez Nuñez Diego Eduardo

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.model_selection import LeaveOneOut
from sklearn.model_selection import KFold
from sklearn.utils import resample

## I. Utilizando el dataset metodosDeValidacion.csv elabore un programa en python que realice lo siguiente:


### Sin mezclar los datos genere un conjunto de entrenamiento (60%) y uno de prueba (40%).

In [2]:
df = pd.read_csv('metodosDeValidacion.csv')
df

x   y
0    1   2
1    2   4
2    3   6
3    4   8
4    5  10
5    6  12
6    7  14
7    8  16
8    9  18
9   10  20
10  11  22
11  12  24
12  13  26
13  14  28
14  15  30
15  16  32
16  17  34
17  18  36
18  19  38
19  20  40

In [3]:
x = df.drop('y', axis=1).values
y = df['y'].values
x,y

(array([[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20]]),
 array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
        36, 38, 40]))

In [4]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.4, shuffle=False)

### Con validación cruzada genere conjuntos de validación para k=3.

In [5]:
def validacionCruzada(x_train,y_train,k):
    print('\n -------------------- \n')
    print('Validacion Cruzada')
    kf = KFold(n_splits=k)
    print('\n X \n')
    for train, test in kf.split(x_train):
        print(x_train[train] ,',', x_train[test])
    print('\n Y \n')
    for train, test in kf.split(y_train):
        print(y_train[train],',', y_train[test])

In [6]:
validacionCruzada(x_train,y_train,3)


 -------------------- 

Validacion Cruzada

 X 

[[ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]] , [[1]
 [2]
 [3]
 [4]]
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 9]
 [10]
 [11]
 [12]] , [[5]
 [6]
 [7]
 [8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]] , [[ 9]
 [10]
 [11]
 [12]]

 Y 

[10 12 14 16 18 20 22 24] , [2 4 6 8]
[ 2  4  6  8 18 20 22 24] , [10 12 14 16]
[ 2  4  6  8 10 12 14 16] , [18 20 22 24]


### Genere conjuntos de validación con Leave One Out

In [7]:
def dejarUnoFuera(x_train,y_train):
    print('\n -------------------- \n')
    print('Leave One Out')
    loo = LeaveOneOut()
    print(loo.get_n_splits(x_train))
    print('\n X \n')
    for i, (train_index, test_index) in enumerate(loo.split(x_train)):
        print('\n',i,x_train[train_index],',', x_train[test_index])
    print('\n Y \n')
    for i, (train_index, test_index) in enumerate(loo.split(y_train)):
        print('\n',i,y_train[train_index],',', y_train[test_index])

In [8]:
dejarUnoFuera(x_train,y_train)


 -------------------- 

Leave One Out
12

 X 


 0 [[ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]] , [[1]]

 1 [[ 1]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]] , [[2]]

 2 [[ 1]
 [ 2]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]] , [[3]]

 3 [[ 1]
 [ 2]
 [ 3]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]] , [[4]]

 4 [[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]] , [[5]]

 5 [[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]] , [[6]]

 6 [[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]] , [[7]]

 7 [[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 9]
 [10]
 [11]
 [12]] , [[8]]

 8 [[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [10]
 [11]
 [12]] , [[9]]

 9 [[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [11]
 [12]] , [[10]]

 10 [[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [12]] , [[11]]

 11 [[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]] , [[12]]

### Utilizando Bootstrap genere 2 conjuntos de validación con conjuntos de entrenamiento de tamaño=5


In [9]:
def Bootstrap(x_train,y_train,nc,m):
    print('\n -------------------- \n')
    print('Bootstrap')
    print('\n X \n')
    for i in range(nc):
        train = resample(x_train, n_samples=m)
        test = np.array([x for x in x_train if x not in train])
        print('train',train,'test',test)
    print('\n Y \n')
    for i in range(nc):
        train = resample(y_train, n_samples=m)
        test = np.array([x for x in y_train if x not in train])
        print('train',train,'test',test)

In [10]:
Bootstrap(x_train,y_train,2,5)


 -------------------- 

Bootstrap

 X 

train [[ 1]
 [ 3]
 [ 7]
 [10]
 [ 4]] test [[ 2]
 [ 5]
 [ 6]
 [ 8]
 [ 9]
 [11]
 [12]]
train [[4]
 [8]
 [3]
 [4]
 [3]] test [[ 1]
 [ 2]
 [ 5]
 [ 6]
 [ 7]
 [ 9]
 [10]
 [11]
 [12]]

 Y 

train [10 12 16 12 10] test [ 2  4  6  8 14 18 20 22 24]
train [ 6 22  4  6 14] test [ 2  8 10 12 16 18 20 24]
